//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryMagix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public string ERROR_PROCEDURE { get; set; }
        public Nullable<int> ERROR_LINE { get; set; }
        public Nullable<int> ERROR_NUMBER { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public System.DateTime ERROR_TIME { get; set; }
        public string ERROR_TYPE { get; set; }
    }
}
