//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryMagix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HST_TRN_InvoiceDetails
    {
        public long TRN_InvoiceDetails_ID { get; set; }
        public string InvoiceNo { get; set; }
        public long TRN_PalletSerialNo_ID { get; set; }
        public string PalletSerial_No { get; set; }
        public long TRN_BoxSerialNo_ID { get; set; }
        public string BoxSerialNo { get; set; }
        public long TRN_BoxBarcodeDetails_ID { get; set; }
        public string BoxBatchCode { get; set; }
        public long Invoice_Qty { get; set; }
        public long Pallet_Qty { get; set; }
        public long Machine_ID { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public Nullable<System.DateTime> HST_Created_On { get; set; }
    }
}
