//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryMagix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Cust_Bosch_PartNo_Rel
    {
        public int Sr_No { get; set; }
        public Nullable<long> Customer_Code { get; set; }
        public string Customer_PartNo { get; set; }
        public string Bosch_PartNo { get; set; }
        public string Kanban_ID { get; set; }
    }
}
