//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryMagix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MST_Module()
        {
            this.MST_Form = new HashSet<MST_Form>();
            this.MST_SubModule = new HashSet<MST_SubModule>();
        }
    
        public long Module_ID { get; set; }
        public string Module_Name { get; set; }
        public string Module_Description { get; set; }
        public Nullable<int> Module_Order { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime Created_On { get; set; }
        public long Created_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public Nullable<long> Modified_By { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_Form> MST_Form { get; set; }
        public virtual MST_User MST_User { get; set; }
        public virtual MST_User MST_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_SubModule> MST_SubModule { get; set; }
    }
}
