//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryMagix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MST_Customer()
        {
            this.MST_PartConfiguration = new HashSet<MST_PartConfiguration>();
        }
    
        public long MST_Customer_ID { get; set; }
        public string Customer_Code { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Index { get; set; }
        public string Address_Line1 { get; set; }
        public string Address_Line2 { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string EmailId { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
    
        public virtual MST_User MST_User { get; set; }
        public virtual MST_User MST_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_PartConfiguration> MST_PartConfiguration { get; set; }
    }
}
