//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryMagix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MST_User()
        {
            this.MST_Customer = new HashSet<MST_Customer>();
            this.MST_Customer1 = new HashSet<MST_Customer>();
            this.MST_Form = new HashSet<MST_Form>();
            this.MST_Form1 = new HashSet<MST_Form>();
            this.MST_Machine = new HashSet<MST_Machine>();
            this.MST_Machine1 = new HashSet<MST_Machine>();
            this.MST_Module = new HashSet<MST_Module>();
            this.MST_Module1 = new HashSet<MST_Module>();
            this.MST_PartConfiguration = new HashSet<MST_PartConfiguration>();
            this.MST_PartConfiguration1 = new HashSet<MST_PartConfiguration>();
            this.MST_SubModule = new HashSet<MST_SubModule>();
            this.MST_SubModule1 = new HashSet<MST_SubModule>();
            this.TRN_BoxSerialNo = new HashSet<TRN_BoxSerialNo>();
            this.TRN_BoxSerialNo1 = new HashSet<TRN_BoxSerialNo>();
            this.TRN_InvoiceDetails = new HashSet<TRN_InvoiceDetails>();
            this.TRN_InvoiceDetails1 = new HashSet<TRN_InvoiceDetails>();
            this.TRN_ScanPartBarcode = new HashSet<TRN_ScanPartBarcode>();
            this.TRN_ScanPartBarcode1 = new HashSet<TRN_ScanPartBarcode>();
        }
    
        public long User_ID { get; set; }
        public long Role_ID { get; set; }
        public string Login_ID { get; set; }
        public string Password { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Middle_Name { get; set; }
        public string EmailId { get; set; }
        public byte[] User_Image { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public string Mobile_No { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<bool> IsFingerPrint { get; set; }
        public bool IsActive { get; set; }
        public long Created_By { get; set; }
        public System.DateTime Created_On { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_Customer> MST_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_Customer> MST_Customer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_Form> MST_Form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_Form> MST_Form1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_Machine> MST_Machine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_Machine> MST_Machine1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_Module> MST_Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_Module> MST_Module1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_PartConfiguration> MST_PartConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_PartConfiguration> MST_PartConfiguration1 { get; set; }
        public virtual MST_Role MST_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_SubModule> MST_SubModule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MST_SubModule> MST_SubModule1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_BoxSerialNo> TRN_BoxSerialNo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_BoxSerialNo> TRN_BoxSerialNo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_InvoiceDetails> TRN_InvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_InvoiceDetails> TRN_InvoiceDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_ScanPartBarcode> TRN_ScanPartBarcode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_ScanPartBarcode> TRN_ScanPartBarcode1 { get; set; }
    }
}
