//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryMagix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_PartConfiguration
    {
        public long MST_PartConfiguration_ID { get; set; }
        public string BoschPart_No { get; set; }
        public string Customer_Index { get; set; }
        public long MST_Customer_ID { get; set; }
        public string BoschPart_Desc { get; set; }
        public string CustPart_No { get; set; }
        public long NoOfPartQy_Box { get; set; }
        public string Packed_In { get; set; }
        public string Line_Id { get; set; }
        public string Line_No { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
    
        public virtual MST_Customer MST_Customer { get; set; }
        public virtual MST_User MST_User { get; set; }
        public virtual MST_User MST_User1 { get; set; }
    }
}
