//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryMagix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_UserForm
    {
        public long Sr_No { get; set; }
        public long User_Id { get; set; }
        public long Frm_Id { get; set; }
        public bool Flag_Visible { get; set; }
        public long Created_By { get; set; }
        public System.DateTime Created_On { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
    }
}
