//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryMagix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_PalletSerialNo
    {
        public long TRN_PalletSerialNo_ID { get; set; }
        public string Invoice_No { get; set; }
        public string InvoiceDate { get; set; }
        public string PalletSrNo { get; set; }
        public string PalletBatchCode { get; set; }
        public string PalletBarcode { get; set; }
        public long InvoiceQty { get; set; }
        public long Machine_ID { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
    }
}
