//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryMagix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_PalletLable_Verify
    {
        public string Invoice_No { get; set; }
        public string PartConfig_Id { get; set; }
        public long InvoiceQty { get; set; }
        public string InvoiceDate { get; set; }
        public Nullable<long> Machine_ID { get; set; }
        public Nullable<long> Created_By { get; set; }
        public string BoxBatchCode { get; set; }
        public string BoxSerialNo { get; set; }
        public string Code { get; set; }
    }
}
