//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryMagix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TRN_BoxSerialNo
    {
        public long TRN_BoxSerialNo_ID { get; set; }
        public long MST_PartConfiguration_ID { get; set; }
        public string BoxSerial_No { get; set; }
        public string BoxBatchCode { get; set; }
        public string BoxBarcode { get; set; }
        public long ActualPart_Qty { get; set; }
        public long Machine_ID { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
    }
}
